# prospector
- id: doi:10.1002/ppj2.20024
  image: https://play-lh.googleusercontent.com/VQ6Zl0NTlOSbssmUbxFr6u76uRaxgCGoTSlvMD-xshcsRsn-BaI_xs44tHX6yslJcw=s360
  extra-links:
    - type: journal
      link: https://doi.org/10.1002/ppj2.20024
    - type: preprint
      link: https://arxiv.org/abs/2104.07071v1
    - type: googleplay
      link: org.phenoapps.prospector
  tags:
    - spectroscopy
    - data management

# waves
- id: doi:10.1002/ppj2.20012
  image: https://raw.githubusercontent.com/GoreLab/waves/master/logo.png
  extra-links:
    - type: journal
      link: https://doi.org/10.1002/ppj2.20012
    - type: preprint
      link: https://doi.org/10.1101/2020.09.18.278549
    - type: github
      link: GoreLab/waves
    - type: package
      link: https://CRAN.R-project.org/package=waves
  tags:
    - spectroscopy
    - R
    - data management

# COPB review
- id: doi:10.1016/j.pbi.2021.102150
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1369526621001515-gr1.jpg
  extra-links:
    - type: journal
      link: https://doi.org/10.1016/j.pbi.2021.102150
  tags:
    - spectroscopy
    - phenomic selection

# sweet corn transcriptomics
- id: doi:10.1002/tpg2.20197
  image: https://raw.githubusercontent.com/jmh579/jmh579.github.io/master/assets/images/lab_landscape.jpg
  extra-links:
    - type: journal
      link: https://doi.org/10.1002/tpg2.20197
    - type: preprint
      link: https://doi.org/10.1101/2021.09.24.461734
    - type: github
      link: GoreLab/SweetCornRNA
    - type: data
      link: https://datacommons.cyverse.org/browse/iplant/home/shared/GoreLab/dataFromPubs/Hershberger_SweetCornRNA_2021
  tags:
    - transcriptomics
    - sweet corn
    - nutritional quality

# cassava nirs
- id: doi:10.1002/ppj2.20040
  image: https://raw.githubusercontent.com/jmh579/jmh579.github.io/master/assets/images/nacrri.jpg
  extra-links:
    - type: journal
      link: https://doi.org/10.1002/ppj2.20040
    - type: preprint
      link: https://doi.org/10.1101/2021.04.30.441802
    - type: github
      link: GoreLab/CassavaNIRS
    - type: data
      link: https://datacommons.cyverse.org/browse/iplant/home/shared/GoreLab/dataFromPubs/Hershberger_CassavaNIRS_2021
  tags:
    - spectroscopy
    - cassava

# breedbase
- id: doi:10.1093/g3journal/jkac078
  image: https://breedbase.org/img/Breedbase_HighRes.png
  extra-links:
    - type: journal
    -link: https://doi.org/10.1093/g3journal/jkac078
  tags:
    - data management
